[2021-09-13 08:06:12,306] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:30 - No module named 'message_handlers.mask_handler'
[2021-09-13 08:06:12,309] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:39 - No module named 'message_handlers.track_handler'
[2021-09-13 08:06:12,312] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:48 - No module named 'message_handlers.pose_handler'
[2021-09-13 08:06:12,314] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:57 - No module named 'message_handlers.depth_handler'
[2021-09-13 08:06:12,316] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:67 - No module named 'message_handlers.track_sort_handler'
[2021-09-13 08:06:12,319] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:76 - No module named 'message_handlers.pose_depth_handler'
[2021-09-13 08:06:12,322] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:85 - No module named 'message_handlers.face_handler'
[2021-09-13 08:06:12,324] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:94 - No module named 'message_handlers.track_sort_handler_experimentation'
[2021-09-13 08:06:12,326] [WARNING] message_handlers /workspace/src/message_handlers/__init__.py:103 - No module named 'message_handlers.object_handler'
[2021-09-13 08:06:15,335] [INFO] hubconf /workspace/src/module_object/hubconf.py:19 - Loaded Module: object_handler.py
[2021-09-13 08:06:15,349] [INFO] module_object.detection /workspace/src/module_object/detection.py:91 - Using default weights: yolov5m.pt
[2021-09-13 08:06:16,708] [INFO] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:28 - Loaded Module: object_handler.py
[2021-09-13 08:06:16,712] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:36 - CAPX_OBJECT_FILTER not found in docker environment.
[2021-09-13 08:06:16,820] [WARNING] root /workspace/src/baseworker_controller.py:57 - OPT_REQUEUE_ON_FAILURE not defined, defaulting to 0 (False)
[2021-09-13 08:06:22,867] [WARNING] message_handlers.objectV5_handler /workspace/src/message_handlers/objectV5_handler.py:141 - AttributeError("'list' object has no attribute 'split'")
[2021-09-13 08:06:22,874] [WARNING] baseworker_controller /workspace/src/baseworker_controller.py:370 - No downstream defined! Not sending message after message handler returns
[2021-09-13 08:08:29,045] [WARNING] __main__ main.py:182 - closing all external connections
[2021-09-13 08:08:29,051] [WARNING] __main__ main.py:192 - asyncmain cancelled
[2021-09-13 08:08:29,056] [WARNING] __main__ main.py:194 - asyncmain exiting
